// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Karel_Gortz.Data;

#nullable disable

namespace Project_Karel_Gortz.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220613102834_services")]
    partial class services
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Database.FixtureDb", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("Awaygoals")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Referee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Round")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Season")
                        .HasColumnType("int");

                    b.Property<int?>("Timestamp")
                        .HasColumnType("int");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("VenueId");

                    b.ToTable("Fixtures");

                    b.HasData(
                        new
                        {
                            Id = 719349,
                            AwayTeamId = 2,
                            Awaygoals = 1,
                            Date = "2021-08-13T18:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 1,
                            LeagueId = 1,
                            Referee = "M. Fritz",
                            Round = "Regular Season - 1",
                            Season = 2021,
                            Timestamp = 1628879400,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 719358,
                            AwayTeamId = 4,
                            Awaygoals = 2,
                            Date = "2021-08-22T15:30:00+00:00",
                            HomeGoals = 3,
                            HomeTeamId = 3,
                            LeagueId = 2,
                            Referee = "M. Petersen",
                            Round = "Regular Season - 2",
                            Season = 2021,
                            Timestamp = 1629646200,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 719367,
                            AwayTeamId = 6,
                            Awaygoals = 0,
                            Date = "2021-08-28T16:30:00+00:00",
                            HomeGoals = 5,
                            HomeTeamId = 5,
                            LeagueId = 3,
                            Referee = "S. Jablonski",
                            Round = "Regular Season - 3",
                            Season = 2021,
                            Timestamp = 1630168200,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 719376,
                            AwayTeamId = 8,
                            Awaygoals = 4,
                            Date = "2021-09-11T16:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 7,
                            LeagueId = 4,
                            Referee = "D. Aytekin",
                            Round = "Regular Season - 4",
                            Season = 2021,
                            Timestamp = 1631377800,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 719385,
                            AwayTeamId = 10,
                            Awaygoals = 0,
                            Date = "2021-09-18T13:30:00+00:00",
                            HomeGoals = 7,
                            HomeTeamId = 9,
                            LeagueId = 5,
                            Referee = "T. Welz",
                            Round = "Regular Season - 5",
                            Season = 2021,
                            Timestamp = 1631971800,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 719402,
                            AwayTeamId = 12,
                            Awaygoals = 3,
                            Date = "2021-09-24T18:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 11,
                            LeagueId = 6,
                            Referee = "R. Schröder",
                            Round = "Regular Season - 6",
                            Season = 2021,
                            Timestamp = 1632508200,
                            VenueId = 6
                        },
                        new
                        {
                            Id = 719403,
                            AwayTeamId = 14,
                            Awaygoals = 2,
                            Date = "2021-10-03T15:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 13,
                            LeagueId = 7,
                            Referee = "F. Badstübner",
                            Round = "Regular Season - 7",
                            Season = 2021,
                            Timestamp = 1633275000,
                            VenueId = 7
                        },
                        new
                        {
                            Id = 719414,
                            AwayTeamId = 16,
                            Awaygoals = 5,
                            Date = "2021-10-17T13:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 15,
                            LeagueId = 8,
                            Referee = "S. Jablonski",
                            Round = "Regular Season - 8",
                            Season = 2021,
                            Timestamp = 1634477400,
                            VenueId = 8
                        },
                        new
                        {
                            Id = 719421,
                            AwayTeamId = 18,
                            Awaygoals = 0,
                            Date = "2021-10-23T13:30:00+00:00",
                            HomeGoals = 4,
                            HomeTeamId = 17,
                            LeagueId = 9,
                            Referee = "M. Jöllenbeck",
                            Round = "Regular Season - 9",
                            Season = 2021,
                            Timestamp = 1634995800,
                            VenueId = 9
                        },
                        new
                        {
                            Id = 719433,
                            AwayTeamId = 20,
                            Awaygoals = 5,
                            Date = "2021-10-30T13:30:00+00:00",
                            HomeGoals = 2,
                            HomeTeamId = 19,
                            LeagueId = 10,
                            Referee = "H. Osmers",
                            Round = "Regular Season - 10",
                            Season = 2021,
                            Timestamp = 1635600600,
                            VenueId = 10
                        },
                        new
                        {
                            Id = 719439,
                            AwayTeamId = 22,
                            Awaygoals = 1,
                            Date = "2021-11-06T14:30:00+00:00",
                            HomeGoals = 2,
                            HomeTeamId = 21,
                            LeagueId = 11,
                            Referee = "S. Stegemann",
                            Round = "Regular Season - 11",
                            Season = 2021,
                            Timestamp = 1636209000,
                            VenueId = 11
                        },
                        new
                        {
                            Id = 719455,
                            AwayTeamId = 24,
                            Awaygoals = 1,
                            Date = "2021-11-19T19:30:00+00:00",
                            HomeGoals = 2,
                            HomeTeamId = 23,
                            LeagueId = 12,
                            Referee = "D. Siebert",
                            Round = "Regular Season - 12",
                            Season = 2021,
                            Timestamp = 1637350200,
                            VenueId = 12
                        },
                        new
                        {
                            Id = 719457,
                            AwayTeamId = 26,
                            Awaygoals = 0,
                            Date = "2021-11-27T17:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 25,
                            LeagueId = 13,
                            Referee = "M. Fritz",
                            Round = "Regular Season - 13",
                            Season = 2021,
                            Timestamp = 1638034200,
                            VenueId = 13
                        },
                        new
                        {
                            Id = 719466,
                            AwayTeamId = 28,
                            Awaygoals = 3,
                            Date = "2021-12-04T17:30:00+00:00",
                            HomeGoals = 2,
                            HomeTeamId = 27,
                            LeagueId = 14,
                            Referee = "F. Zwayer",
                            Round = "Regular Season - 14",
                            Season = 2021,
                            Timestamp = 1638639000,
                            VenueId = 14
                        },
                        new
                        {
                            Id = 719475,
                            AwayTeamId = 30,
                            Awaygoals = 1,
                            Date = "2021-12-11T14:30:00+00:00",
                            HomeGoals = 2,
                            HomeTeamId = 29,
                            LeagueId = 15,
                            Referee = "B. Cortus",
                            Round = "Regular Season - 15",
                            Season = 2021,
                            Timestamp = 1639233000,
                            VenueId = 15
                        },
                        new
                        {
                            Id = 719489,
                            AwayTeamId = 32,
                            Awaygoals = 5,
                            Date = "2021-12-14T17:30:00+00:00",
                            HomeGoals = 0,
                            HomeTeamId = 31,
                            LeagueId = 16,
                            Referee = "R. Schröder",
                            Round = "Regular Season - 16",
                            Season = 2021,
                            Timestamp = 1639503000,
                            VenueId = 16
                        },
                        new
                        {
                            Id = 719493,
                            AwayTeamId = 34,
                            Awaygoals = 0,
                            Date = "2021-12-17T19:30:00+00:00",
                            HomeGoals = 4,
                            HomeTeamId = 33,
                            LeagueId = 17,
                            Referee = "T. Welz",
                            Round = "Regular Season - 17",
                            Season = 2021,
                            Timestamp = 1639769400,
                            VenueId = 17
                        },
                        new
                        {
                            Id = 719502,
                            AwayTeamId = 36,
                            Awaygoals = 2,
                            Date = "2022-01-07T19:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 35,
                            LeagueId = 18,
                            Referee = "D. Siebert",
                            Round = "Regular Season - 18",
                            Season = 2021,
                            Timestamp = 1641583800,
                            VenueId = 18
                        },
                        new
                        {
                            Id = 719519,
                            AwayTeamId = 38,
                            Awaygoals = 4,
                            Date = "2022-01-15T14:30:00+00:00",
                            HomeGoals = 0,
                            HomeTeamId = 37,
                            LeagueId = 19,
                            Referee = "T. Welz",
                            Round = "Regular Season - 19",
                            Season = 2021,
                            Timestamp = 1642257000,
                            VenueId = 19
                        },
                        new
                        {
                            Id = 719526,
                            AwayTeamId = 40,
                            Awaygoals = 4,
                            Date = "2022-01-23T16:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 39,
                            LeagueId = 20,
                            Referee = "B. Dankert",
                            Round = "Regular Season - 20",
                            Season = 2021,
                            Timestamp = 1642955400,
                            VenueId = 20
                        },
                        new
                        {
                            Id = 719529,
                            AwayTeamId = 42,
                            Awaygoals = 2,
                            Date = "2022-02-05T17:30:00+00:00",
                            HomeGoals = 3,
                            HomeTeamId = 41,
                            LeagueId = 21,
                            Referee = "S. Jablonski",
                            Round = "Regular Season - 21",
                            Season = 2021,
                            Timestamp = 1644082200,
                            VenueId = 21
                        },
                        new
                        {
                            Id = 719545,
                            AwayTeamId = 44,
                            Awaygoals = 2,
                            Date = "2022-02-12T14:30:00+00:00",
                            HomeGoals = 4,
                            HomeTeamId = 43,
                            LeagueId = 22,
                            Referee = "R. Schröder",
                            Round = "Regular Season - 22",
                            Season = 2021,
                            Timestamp = 1644676200,
                            VenueId = 22
                        },
                        new
                        {
                            Id = 719547,
                            AwayTeamId = 46,
                            Awaygoals = 1,
                            Date = "2022-02-20T14:30:00+00:00",
                            HomeGoals = 4,
                            HomeTeamId = 45,
                            LeagueId = 23,
                            Referee = "R. Hartmann",
                            Round = "Regular Season - 23",
                            Season = 2021,
                            Timestamp = 1645367400,
                            VenueId = 23
                        },
                        new
                        {
                            Id = 719556,
                            AwayTeamId = 48,
                            Awaygoals = 1,
                            Date = "2022-02-26T17:30:00+00:00",
                            HomeGoals = 0,
                            HomeTeamId = 47,
                            LeagueId = 24,
                            Referee = "F. Badstübner",
                            Round = "Regular Season - 24",
                            Season = 2021,
                            Timestamp = 1645896600,
                            VenueId = 24
                        },
                        new
                        {
                            Id = 719565,
                            AwayTeamId = 50,
                            Awaygoals = 1,
                            Date = "2022-03-05T14:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 49,
                            LeagueId = 25,
                            Referee = "D. Siebert",
                            Round = "Regular Season - 25",
                            Season = 2021,
                            Timestamp = 1646490600,
                            VenueId = 25
                        },
                        new
                        {
                            Id = 719580,
                            AwayTeamId = 52,
                            Awaygoals = 1,
                            Date = "2022-03-12T14:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 51,
                            LeagueId = 26,
                            Referee = "R. Schröder",
                            Round = "Regular Season - 26",
                            Season = 2021,
                            Timestamp = 1647095400,
                            VenueId = 26
                        },
                        new
                        {
                            Id = 719583,
                            AwayTeamId = 54,
                            Awaygoals = 0,
                            Date = "2022-03-19T17:30:00+00:00",
                            HomeGoals = 4,
                            HomeTeamId = 53,
                            LeagueId = 27,
                            Referee = "H. Osmers",
                            Round = "Regular Season - 27",
                            Season = 2021,
                            Timestamp = 1647711000,
                            VenueId = 27
                        },
                        new
                        {
                            Id = 719597,
                            AwayTeamId = 56,
                            Awaygoals = 4,
                            Date = "2022-04-02T13:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 55,
                            LeagueId = 28,
                            Referee = "C. Dingert",
                            Round = "Regular Season - 28",
                            Season = 2021,
                            Timestamp = 1648906200,
                            VenueId = 28
                        },
                        new
                        {
                            Id = 719601,
                            AwayTeamId = 58,
                            Awaygoals = 0,
                            Date = "2022-04-09T13:30:00+00:00",
                            HomeGoals = 1,
                            HomeTeamId = 57,
                            LeagueId = 29,
                            Referee = "P. Ittrich",
                            Round = "Regular Season - 29",
                            Season = 2021,
                            Timestamp = 1649511000,
                            VenueId = 29
                        },
                        new
                        {
                            Id = 719618,
                            AwayTeamId = 60,
                            Awaygoals = 3,
                            Date = "2022-04-17T13:30:00+00:00",
                            HomeGoals = 0,
                            HomeTeamId = 59,
                            LeagueId = 30,
                            Referee = "M. Jöllenbeck",
                            Round = "Regular Season - 30",
                            Season = 2021,
                            Timestamp = 1650202200,
                            VenueId = 30
                        },
                        new
                        {
                            Id = 719619,
                            AwayTeamId = 62,
                            Awaygoals = 1,
                            Date = "2022-04-23T16:30:00+00:00",
                            HomeGoals = 3,
                            HomeTeamId = 61,
                            LeagueId = 31,
                            Referee = "D. Siebert",
                            Round = "Regular Season - 31",
                            Season = 2021,
                            Timestamp = 1650731400,
                            VenueId = 31
                        },
                        new
                        {
                            Id = 719634,
                            AwayTeamId = 64,
                            Awaygoals = 1,
                            Date = "2022-04-30T13:30:00+00:00",
                            HomeGoals = 3,
                            HomeTeamId = 63,
                            LeagueId = 32,
                            Referee = "S. Stegemann",
                            Round = "Regular Season - 32",
                            Season = 2021,
                            Timestamp = 1651325400,
                            VenueId = 32
                        },
                        new
                        {
                            Id = 719637,
                            AwayTeamId = 66,
                            Awaygoals = 2,
                            Date = "2022-05-08T15:30:00+00:00",
                            HomeGoals = 2,
                            HomeTeamId = 65,
                            LeagueId = 33,
                            Referee = "D. Aytekin",
                            Round = "Regular Season - 33",
                            Season = 2021,
                            Timestamp = 1652023800,
                            VenueId = 33
                        },
                        new
                        {
                            Id = 719647,
                            AwayTeamId = 68,
                            Awaygoals = 2,
                            Date = "2022-05-14T13:30:00+00:00",
                            HomeGoals = 2,
                            HomeTeamId = 67,
                            LeagueId = 34,
                            Referee = "R. Hartmann",
                            Round = "Regular Season - 34",
                            Season = 2021,
                            Timestamp = 1652535000,
                            VenueId = 34
                        });
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Database.LeagueDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 12,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 13,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 15,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 16,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 17,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 18,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 19,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 20,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 21,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 22,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 23,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 24,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 25,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 26,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 27,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 28,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 29,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 30,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 31,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 32,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 33,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        },
                        new
                        {
                            Id = 34,
                            Country = "Germany",
                            Flag = "https://media.api-sports.io/flags/de.svg",
                            LeagueId = 78,
                            Logo = "https://media.api-sports.io/football/leagues/78.png",
                            Name = "Bundesliga 1"
                        });
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Database.TeamDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Fixtureid")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fixtureid");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Logo = "https://media.api-sports.io/football/teams/163.png",
                            Name = "Borussia Monchengladbach",
                            TeamId = 163
                        },
                        new
                        {
                            Id = 2,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 3,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 4,
                            Logo = "https://media.api-sports.io/football/teams/192.png",
                            Name = "FC Koln",
                            TeamId = 192
                        },
                        new
                        {
                            Id = 5,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 6,
                            Logo = "https://media.api-sports.io/football/teams/159.png",
                            Name = "Hertha Berlin",
                            TeamId = 159
                        },
                        new
                        {
                            Id = 7,
                            Logo = "https://media.api-sports.io/football/teams/173.png",
                            Name = "RB Leipzig",
                            TeamId = 173
                        },
                        new
                        {
                            Id = 8,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 9,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 10,
                            Logo = "https://media.api-sports.io/football/teams/176.png",
                            Name = "VfL BOCHUM",
                            TeamId = 176
                        },
                        new
                        {
                            Id = 11,
                            Logo = "https://media.api-sports.io/football/teams/178.png",
                            Name = "SpVgg Greuther Furth",
                            TeamId = 178
                        },
                        new
                        {
                            Id = 12,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 13,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 14,
                            Logo = "https://media.api-sports.io/football/teams/169.png",
                            Name = "Eintracht Frankfurt",
                            TeamId = 169
                        },
                        new
                        {
                            Id = 15,
                            Logo = "https://media.api-sports.io/football/teams/168.png",
                            Name = "Bayer Leverkusen",
                            TeamId = 168
                        },
                        new
                        {
                            Id = 16,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 17,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 18,
                            Logo = "https://media.api-sports.io/football/teams/167.png",
                            Name = "1899 Hoffenheim",
                            TeamId = 167
                        },
                        new
                        {
                            Id = 19,
                            Logo = "https://media.api-sports.io/football/teams/182.png",
                            Name = "Union Berlin",
                            TeamId = 182
                        },
                        new
                        {
                            Id = 20,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 21,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 22,
                            Logo = "https://media.api-sports.io/football/teams/160.png",
                            Name = "SC Freiburg",
                            TeamId = 160
                        },
                        new
                        {
                            Id = 23,
                            Logo = "https://media.api-sports.io/football/teams/170.png",
                            Name = "FC Augsburg",
                            TeamId = 170
                        },
                        new
                        {
                            Id = 24,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 25,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 26,
                            Logo = "https://media.api-sports.io/football/teams/188.png",
                            Name = "Arminia Bielefeld",
                            TeamId = 188
                        },
                        new
                        {
                            Id = 27,
                            Logo = "https://media.api-sports.io/football/teams/165.png",
                            Name = "Borussia Dortmund",
                            TeamId = 165
                        },
                        new
                        {
                            Id = 28,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 29,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 30,
                            Logo = "https://media.api-sports.io/football/teams/164.png",
                            Name = "FSV Mainz 05",
                            TeamId = 164
                        },
                        new
                        {
                            Id = 31,
                            Logo = "https://media.api-sports.io/football/teams/172.png",
                            Name = "VfB Stuttgart",
                            TeamId = 172
                        },
                        new
                        {
                            Id = 32,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 33,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 34,
                            Logo = "https://media.api-sports.io/football/teams/161.png",
                            Name = "VfL Wolfsburg",
                            TeamId = 161
                        },
                        new
                        {
                            Id = 35,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 36,
                            Logo = "https://media.api-sports.io/football/teams/163.png",
                            Name = "Borussia Monchengladbach",
                            TeamId = 163
                        },
                        new
                        {
                            Id = 37,
                            Logo = "https://media.api-sports.io/football/teams/192.png",
                            Name = "FC Koln",
                            TeamId = 192
                        },
                        new
                        {
                            Id = 38,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 39,
                            Logo = "https://media.api-sports.io/football/teams/159.png",
                            Name = "Hertha Berlin",
                            TeamId = 159
                        },
                        new
                        {
                            Id = 40,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 41,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 42,
                            Logo = "https://media.api-sports.io/football/teams/173.png",
                            Name = "RB Leipzig",
                            TeamId = 173
                        },
                        new
                        {
                            Id = 43,
                            Logo = "https://media.api-sports.io/football/teams/176.png",
                            Name = "VfL BOCHUM",
                            TeamId = 176
                        },
                        new
                        {
                            Id = 44,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 45,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 46,
                            Logo = "https://media.api-sports.io/football/teams/178.png",
                            Name = "SpVgg Greuther Furth",
                            TeamId = 178
                        },
                        new
                        {
                            Id = 47,
                            Logo = "https://media.api-sports.io/football/teams/169.png",
                            Name = "Eintracht Frankfurt",
                            TeamId = 169
                        },
                        new
                        {
                            Id = 48,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 49,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 50,
                            Logo = "https://media.api-sports.io/football/teams/168.png",
                            Name = "Bayer Leverkusen",
                            TeamId = 168
                        },
                        new
                        {
                            Id = 51,
                            Logo = "https://media.api-sports.io/football/teams/167.png",
                            Name = "1899 Hoffenheim",
                            TeamId = 167
                        },
                        new
                        {
                            Id = 52,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 53,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 54,
                            Logo = "https://media.api-sports.io/football/teams/182.png",
                            Name = "Union Berlin",
                            TeamId = 182
                        },
                        new
                        {
                            Id = 55,
                            Logo = "https://media.api-sports.io/football/teams/160.png",
                            Name = "SC Freiburg",
                            TeamId = 160
                        },
                        new
                        {
                            Id = 56,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 57,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 58,
                            Logo = "https://media.api-sports.io/football/teams/170.png",
                            Name = "FC Augsburg",
                            TeamId = 170
                        },
                        new
                        {
                            Id = 59,
                            Logo = "https://media.api-sports.io/football/teams/188.png",
                            Name = "Arminia Bielefeld",
                            TeamId = 188
                        },
                        new
                        {
                            Id = 60,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 61,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 62,
                            Logo = "https://media.api-sports.io/football/teams/165.png",
                            Name = "Borussia Dortmund",
                            TeamId = 165
                        },
                        new
                        {
                            Id = 63,
                            Logo = "https://media.api-sports.io/football/teams/164.png",
                            Name = "FSV Mainz 05",
                            TeamId = 164
                        },
                        new
                        {
                            Id = 64,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 65,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        },
                        new
                        {
                            Id = 66,
                            Logo = "https://media.api-sports.io/football/teams/172.png",
                            Name = "VfB Stuttgart",
                            TeamId = 172
                        },
                        new
                        {
                            Id = 67,
                            Logo = "https://media.api-sports.io/football/teams/161.png",
                            Name = "VfL Wolfsburg",
                            TeamId = 161
                        },
                        new
                        {
                            Id = 68,
                            Logo = "https://media.api-sports.io/football/teams/157.png",
                            Name = "Bayern Munich",
                            TeamId = 157
                        });
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Database.VenueDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mönchengladbach",
                            Name = "Stadion im BORUSSIA-PARK",
                            VenueId = 703
                        },
                        new
                        {
                            Id = 2,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 3,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 4,
                            City = "Leipzig",
                            Name = "Red Bull Arena",
                            VenueId = 738
                        },
                        new
                        {
                            Id = 5,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 6,
                            City = "Fürth",
                            Name = "Sportpark Ronhof Thomas Sommer",
                            VenueId = 718
                        },
                        new
                        {
                            Id = 7,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 8,
                            City = "Leverkusen",
                            Name = "BayArena",
                            VenueId = 699
                        },
                        new
                        {
                            Id = 9,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 10,
                            City = "Berlin",
                            Name = "Stadion An der Alten Försterei",
                            VenueId = 748
                        },
                        new
                        {
                            Id = 11,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 12,
                            City = "Augsburg",
                            Name = "WWK Arena",
                            VenueId = 698
                        },
                        new
                        {
                            Id = 13,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 14,
                            City = "Dortmund",
                            Name = "Signal-Iduna-Park",
                            VenueId = 702
                        },
                        new
                        {
                            Id = 15,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 16,
                            City = "Stuttgart",
                            Name = "Mercedes-Benz-Arena",
                            VenueId = 750
                        },
                        new
                        {
                            Id = 17,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 18,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 19,
                            City = "Köln",
                            Name = "RheinEnergieStadion",
                            VenueId = 731
                        },
                        new
                        {
                            Id = 20,
                            City = "Berlin",
                            Name = "Olympiastadion Berlin",
                            VenueId = 694
                        },
                        new
                        {
                            Id = 21,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 22,
                            City = "Bochum",
                            Name = "Vonovia Ruhrstadion",
                            VenueId = 751
                        },
                        new
                        {
                            Id = 23,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 24,
                            City = "Frankfurt am Main",
                            Name = "Deutsche Bank Park",
                            VenueId = 10491
                        },
                        new
                        {
                            Id = 25,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 26,
                            City = "Sinsheim",
                            Name = "PreZero Arena",
                            VenueId = 724
                        },
                        new
                        {
                            Id = 27,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 28,
                            City = "Freiburg im Breisgau",
                            Name = "Europa-Park Stadion",
                            VenueId = 12717
                        },
                        new
                        {
                            Id = 29,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 30,
                            City = "Bielefeld",
                            Name = "SchücoArena",
                            VenueId = 697
                        },
                        new
                        {
                            Id = 31,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 32,
                            City = "Mainz",
                            Name = "MEWA ARENA",
                            VenueId = 11899
                        },
                        new
                        {
                            Id = 33,
                            City = "München",
                            Name = "Allianz Arena",
                            VenueId = 700
                        },
                        new
                        {
                            Id = 34,
                            City = "Wolfsburg",
                            Name = "VOLKSWAGEN ARENA",
                            VenueId = 752
                        });
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Posts.Comment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Posts.Post", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FixtureId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("FixtureId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Users.CustomUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Project_Karel_Gortz.Models.Users.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Project_Karel_Gortz.Models.Users.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Karel_Gortz.Models.Users.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Project_Karel_Gortz.Models.Users.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Database.FixtureDb", b =>
                {
                    b.HasOne("Project_Karel_Gortz.Models.Database.LeagueDb", "League")
                        .WithMany("FixtureDbs")
                        .HasForeignKey("LeagueId");

                    b.HasOne("Project_Karel_Gortz.Models.Database.VenueDb", "Venue")
                        .WithMany("FixtureDbs")
                        .HasForeignKey("VenueId");

                    b.Navigation("League");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Database.TeamDb", b =>
                {
                    b.HasOne("Project_Karel_Gortz.Models.Database.FixtureDb", "Fixture")
                        .WithMany("TeamDbs")
                        .HasForeignKey("Fixtureid");

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Posts.Comment", b =>
                {
                    b.HasOne("Project_Karel_Gortz.Models.Users.CustomUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Project_Karel_Gortz.Models.Posts.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Posts.Post", b =>
                {
                    b.HasOne("Project_Karel_Gortz.Models.Users.CustomUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Project_Karel_Gortz.Models.Database.FixtureDb", "Fixture")
                        .WithMany("Posts")
                        .HasForeignKey("FixtureId");

                    b.Navigation("Author");

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Database.FixtureDb", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("TeamDbs");
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Database.LeagueDb", b =>
                {
                    b.Navigation("FixtureDbs");
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Database.VenueDb", b =>
                {
                    b.Navigation("FixtureDbs");
                });

            modelBuilder.Entity("Project_Karel_Gortz.Models.Posts.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
